### PR TITLE
GRD-50

### PR DESCRIPTION
**Pull request by rishi-shah12**

### CODE REVIEW

**Comment by iainrb** [comment]
Mostly this looks good, but I have a couple of questions:

1. Why are there separate workflows in `./imports/pull_star.wdl` and `./submodules/star/star.wdl`? This seems like unnecessary duplication of code. Is it possible to import from `./submodules/star/star.wdl` instead?

2. Out of curiosity, why have you waited until now to make the PR? The last commit was on 7 December last year.

**Comment by iainrb** [comment]
retest this please

**Comment by pruzanov** [comment]
FYI, I just started looking at this workflow. Rishi was working on it, and I believe nobody touched it since then. I will check what's going on with imports, thanks

**Review by iainrb — APPROVED** [review]

**Review by lheisler — APPROVED** [review]
approving with minimal review

**Pull request merged**
